---

- name: Set up pip.ini config
  copy:
    src: files/pip.conf
    dest: /etc/pip.conf
    mode: 0644

- name: Update pip
  pip:
    name: pip
    state: present
  become: yes

- name: Install common pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"
  become: yes
  tags:
    - common-role-pip-packages
