---

- name: Set up pip.ini config
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
    mode: 0644
    owner: root
    group: root

- name: Update pip
  pip:
    name: pip
    state: latest
  become: yes

- name: Install common pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_packages }}"
  become: yes
  tags:
    - common-role-pip-packages
